# -*- coding: utf-8 -*-
"""Linear Regression House Prediction Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14LsyFVLb8lYexLm_9BD5mfjsI_EyMX-B
"""

import numpy as np
import pandas as pd

data= pd.read_csv("/content/Housing.csv")

data.head()

data['mainroad'] = data['mainroad'].apply({'yes': 1, 'no': 0}.get)
data['guestroom'] = data['guestroom'].apply({'yes': 1, 'no': 0}.get)
data['basement'] = data['basement'].apply({'yes': 1, 'no': 0}.get)
data['hotwaterheating'] = data['hotwaterheating'].apply({'yes': 1, 'no': 0}.get)
data['airconditioning'] = data['airconditioning'].apply({'yes': 1, 'no': 0}.get)
data['prefarea'] = data['prefarea'].apply({'yes': 1, 'no': 0}.get)
data['furnishingstatus'] = data['furnishingstatus'].apply({'furnished': 1, 'semi-furnished': 2, 'unfurnished': 3}.get)

data.dropna(inplace=True)
