# -*- coding: utf-8 -*-
"""Linear Regression House Prediction Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14LsyFVLb8lYexLm_9BD5mfjsI_EyMX-B
"""


x= data[['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'parking', 'prefarea', 'furnishingstatus']]

y= data['price']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.8)

from sklearn.linear_model import LinearRegression
Regression= LinearRegression()
Regression.fit(x_train, y_train)
